Imports System.IO

Namespace CodeGen
    Module Handler

        Public ReadOnly Namer As NameGenerator = New NameGenerator()

        Private Includes As New List(Of String) From {"#include <stdio.h>", "#include <stdlib.h>", "#include <stdbool.h>"}
        Private Consts As New HashSet(Of CodeGen.Const)
        Private GlobalVariables As New HashSet(Of CodeGen.GlobalVariable)
        Private Enums As New HashSet(Of CodeGen.Enum)
        Private Structs As New HashSet(Of CodeGen.Struct)
        Private Functions As New HashSet(Of CodeGen.Function)

        Public Sub RegisterInclude(Include As String)
            For Each Inc In Includes
                If Inc = Include Then
                    Exit Sub
                End If
            Next
            Includes.Add(Include)
        End Sub

        Public Sub RegisterConst([Const] As CodeGen.Const)
            Consts.Add([Const])
        End Sub

        Public Sub RegisterGlobalVariable(GlobalVariable As CodeGen.GlobalVariable)
            GlobalVariables.Add(GlobalVariable)
        End Sub

        Public Sub RegisterEnum([Enum] As CodeGen.Enum)
            Enums.Add([Enum])
        End Sub

        Public Sub RegisterStruct(Struct As CodeGen.Struct)
            Structs.Add(Struct)
        End Sub

        Public Sub RegisterFunction([Function] As CodeGen.Function)
            Functions.Add([Function])
        End Sub

        Public Sub AssembleFile(Filepath As String, EntryPoint As String)

            'Create file
            Dim Writer As New StreamWriter(Filepath)

            'Write header
            Writer.WriteLine("/*")
            Writer.WriteLine(vbTab & "This file was auto-generated by the Lim compiler.")
            Writer.WriteLine(vbTab & "Developed by Gémino Ruffault--Ravenel.")
            Writer.WriteLine("*/")

            'Write includes
            For Each Include In Includes
                Writer.WriteLine(Include)
            Next
            Writer.WriteLine()

            'Write function signatures
            For Each Fn In Functions
                Fn.WriteSignature(Writer)
            Next
            Writer.WriteLine()

            'Write functions bodies
            For Each Fn In Functions
                Fn.WriteBody(Writer)
            Next

            'Write entry point
            WriteEntryPoint(Writer, EntryPoint)

            'Close file writer
            Writer.Close()

        End Sub

        Private Sub WriteEntryPoint(Writer As StreamWriter, EntryPoint As String)

            Writer.WriteLine("int main(int argc, char** argv) {")
            Writer.WriteLine(vbTab & $"{EntryPoint}();")
            Writer.WriteLine(vbTab & "return 0;")
            Writer.WriteLine("}")

        End Sub

    End Module
End Namespace