Imports System.IO

Namespace CodeGen
    Module Handler

        Public ReadOnly Namer As NameGenerator = New NameGenerator()

        Private Includes As New HashSet(Of String) From {"<stdio.h>", "<stdlib.h>", "<string.h>", "<stdbool.h>", "<math.h>", "<errno.h>"}
        Private Macros As New List(Of String)
        Private Consts As New HashSet(Of String)
        Private Typedefs As New HashSet(Of String)
        Private GlobalVariables As New HashSet(Of String)
        Private Enums As New HashSet(Of CodeGen.Enum)
        Private Structs As New HashSet(Of CodeGen.Struct)
        Private Functions As New HashSet(Of CodeGen.BaseFunction)

        Public Sub RegisterInclude(Include As String)
            Includes.Add(Include)
        End Sub

        Public Sub RegisterMacro(Macro As String)
            Macros.Add(Macro)
        End Sub

        Public Sub RegisterConst([Const] As String, Comment As String)
            If VERBOSE Then
                Consts.Add([Const] & " // " & Comment)
            Else
                Consts.Add([Const])
            End If
        End Sub

        Public Sub RegisterGlobalVariable(GlobalVariable As String)
            GlobalVariables.Add(GlobalVariable)
        End Sub

        Public Sub RegisterEnum([Enum] As CodeGen.Enum)
            Enums.Add([Enum])
        End Sub

        Public Sub RegisterStruct(Struct As CodeGen.Struct)
            Structs.Add(Struct)
        End Sub

        Public Sub RegisterFunction([Function] As CodeGen.BaseFunction)
            Functions.Add([Function])
        End Sub
        Public Sub RegisterTypedef(Typedef As String)
            Typedefs.Add(Typedef)
        End Sub

        Public Sub AssembleFile(Filepath As String, EntryPoint As ContextedFunction)

            'Write garbage collector
            WriteGarbageCollector()
            WritePanic()
            WriteContext() ' At this point no functions must be registered

            'Clean dir
            Directory.GetParent(Filepath).Create()

            'Create file
            Dim Writer As New StreamWriter(Filepath)

            'Write header
            Writer.WriteLine("/*")
            Writer.WriteLine(vbTab & "This file was auto-generated by the Lim compiler.")
            Writer.WriteLine(vbTab & "Developed by Gémino Ruffault--Ravenel.")
            If VERBOSE Then
                Writer.WriteLine(vbTab & vbTab & Compiler.GetCompilationCommand())
            Else
                Writer.WriteLine(vbTab & "Compile with -v flag to enable verbose and comments.")
            End If
            Writer.WriteLine("*/")
            Writer.WriteLine("")

            'Macros
            WriteTitle(Writer, "Macros")
            For Each Macro In Macros
                Writer.WriteLine(Macro)
            Next
            Writer.WriteLine()

            'Write includes
            WriteTitle(Writer, "Includes")
            For Each Include In Includes
                Writer.WriteLine("#include " & Include)
            Next
            Writer.WriteLine()

            'Write structure types
            WriteTitle(Writer, "Structure signature")
            For Each Struct In Structs
                Struct.WriteSignature(Writer)
            Next
            Writer.WriteLine()

            'Write functions bodies
            WriteTitle(Writer, "Structure bodies")
            For Each Struct In Structs
                Struct.Write(Writer)
            Next
            Writer.WriteLine()

            'Write custom typedef
            WriteTitle(Writer, "Racks typedef")
            For Each Typedef In Typedefs
                Writer.WriteLine(Typedef)
            Next
            Writer.WriteLine()

            'Write consts
            WriteTitle(Writer, "Constants")
            For Each [Const] In Consts
                Writer.WriteLine([Const])
            Next
            Writer.WriteLine()

            'Write global functions
            WriteTitle(Writer, "Global variables")
            For Each GlobalVariable In GlobalVariables
                Writer.WriteLine(GlobalVariable)
            Next
            Writer.WriteLine()

            'Write function signatures
            WriteTitle(Writer, "Function signatures")
            For Each Fn In Functions
                Fn.WriteSignature(Writer)
            Next
            Writer.WriteLine()

            'Write functions bodies
            WriteTitle(Writer, "Function bodies")
            For Each Fn In Functions
                Fn.WriteBody(Writer)
            Next

            'Write entry point
            WriteTitle(Writer, "Entry point")
            WriteEntryPoint(Writer, EntryPoint)

            'Close file writer
            Writer.Close()

        End Sub

        Private Sub WriteTitle(Writer As StreamWriter, Title As String)
            If Not VERBOSE Then
                Exit Sub
            End If
            Dim TitleLine As String = "///// " & Title & " /////"
            Writer.WriteLine(StrDup(TitleLine.Length, "/"))
            Writer.WriteLine(TitleLine)
            Writer.WriteLine(StrDup(TitleLine.Length, "/"))
        End Sub

        Private Sub WriteEntryPoint(Writer As StreamWriter, EntryPoint As ContextedFunction)

            Writer.WriteLine("int main(int argc, char** argv) {")
            Writer.WriteLine(vbTab & "tgc_t* gc = malloc(sizeof(tgc_t));")
            Writer.WriteLine(vbTab & "if (gc == NULL) {printf(""LIM RUNTIME ERROR: not enought memory\n""); return -1;}")
            Writer.WriteLine(vbTab & "tgc_start(gc, &argc);")
            If INTEGRATE_DEBUG Then
                Writer.WriteLine(vbTab & $"{RUNTIME_CONTEXT_STRUCT_NAME} {RUNTIME_CONTEXT_VARIABLE_NAME} = {{NULL, 0, gc}};")
            Else
                Writer.WriteLine(vbTab & $"{RUNTIME_CONTEXT_STRUCT_NAME} {RUNTIME_CONTEXT_VARIABLE_NAME} = {{NULL, gc}};")
            End If
            Writer.WriteLine(vbTab & EntryPoint.WriteCall({}) & ";")
            Writer.WriteLine(vbTab & "tgc_stop(gc);")
            Writer.WriteLine(vbTab & "return 0;")
            Writer.WriteLine("}")

        End Sub

        Private Sub WritePanic()

            If INTEGRATE_DEBUG Then
                RegisterFunction(New BaseFunction(
                    $"void {PANIC_FUNCTION_NAME}({RUNTIME_CONTEXT_STRUCT_NAME} {RUNTIME_CONTEXT_VARIABLE_NAME}, const char* message)",
                    {
                        "fprintf(stderr, ""\n\033[31m=== FATAL RUNTIME ERROR ===\033[0m\n"");",
                        "fprintf(stderr, ""%s\n\n"", message);",
                        "fprintf(stderr, ""---- Stacktrace ----\n"");",
                        $"{PRINT_STACK_TRACE_FUNCTION_NAME}({RUNTIME_CONTEXT_VARIABLE_NAME});",
                        "exit(EXIT_FAILURE);"
                    },
                    "Panic to death"
                ))
            Else
                RegisterFunction(New BaseFunction(
                    $"void {PANIC_FUNCTION_NAME}({RUNTIME_CONTEXT_STRUCT_NAME} {RUNTIME_CONTEXT_VARIABLE_NAME}, const char* message)",
                    {
                        "fprintf(stderr, ""\n\033[31m=== FATAL RUNTIME ERROR ===\033[0m\n"");",
                        "fprintf(stderr, ""%s\n"", message);",
                        "exit(EXIT_FAILURE);"
                    },
                    "Panic to death"
                ))
            End If

        End Sub
        Public Function WritePanicCall(Value As String) As String
            Return $"{PANIC_FUNCTION_NAME}({RUNTIME_CONTEXT_VARIABLE_NAME}, {Value})"
        End Function

        Private Sub WriteContext()

            If INTEGRATE_DEBUG Then
                RegisterStruct(New Struct(RUNTIME_CONTEXT_STRUCT_NAME, {$"{RUNTIME_CONTEXT_STRUCT_NAME}* upper;", "int functionId;", "tgc_t* gc;"}, "Function stack context"))
                RegisterGlobalVariable("static const char* functionNames[] = {" & String.Join(", ", OwnContextFunction.FunctionNames) & "};")
                RegisterFunction(New BaseFunction(
                    $"void {PRINT_STACK_TRACE_FUNCTION_NAME}({RUNTIME_CONTEXT_STRUCT_NAME} {RUNTIME_CONTEXT_VARIABLE_NAME})",
                    {
                        $"{RUNTIME_CONTEXT_STRUCT_NAME} ctx = {RUNTIME_CONTEXT_VARIABLE_NAME};",
                        "int depth = 0;",
                        "while (ctx.upper != NULL){",
                        vbTab & "if (depth > 0){",
                        vbTab & vbTab & "for (int i = 0; i < depth - 1; i++)",
                        vbTab & vbTab & vbTab & "fprintf(stderr, ""|   "");",
                        vbTab & vbTab & "fprintf(stderr, ""|-- "");",
                        vbTab & "}",
                        vbTab & "fprintf(stderr, ""\033[32m%s\033[0m%s\n"", functionNames[ctx.functionId], depth == 0 ? "" < -here"" : """");",
                        vbTab & "ctx = *ctx.upper;",
                        vbTab & "depth++;",
                        "}"
                    },
                    "Print function trace stack"
                ))
            Else
                RegisterStruct(New Struct(RUNTIME_CONTEXT_STRUCT_NAME, {$"{RUNTIME_CONTEXT_STRUCT_NAME}* upper;", "tgc_t* gc;"}, "Function stack context"))
            End If

        End Sub

        Private Sub WriteGarbageCollector()

            RegisterInclude("""" & Path.Combine(Compiler.COMPILER_DIRECTORY, "clibs", "tgc", "tgc.h") & """")
            Compiler.CFilesToInclude.Add(Path.Combine(Compiler.COMPILER_DIRECTORY, "clibs", "tgc", "tgc.c"))

            RegisterMacro($"#define {LIM_ALLOC}(size) tgc_alloc({RUNTIME_CONTEXT_VARIABLE_NAME}.gc, size);")
            RegisterMacro("#define LIM_ALLOC_STANDALONE(gc, size) tgc_alloc(gc, size);")
            RegisterMacro($"#define {LIM_FREE}(ptr) tgc_free({RUNTIME_CONTEXT_VARIABLE_NAME}.gc, ptr);")
            RegisterMacro($"#define {LIM_REALLOC}(ptr, size) tgc_realloc({RUNTIME_CONTEXT_VARIABLE_NAME}.gc, ptr, size);")

        End Sub

    End Module
End Namespace