<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>limc</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="SourceModelisation\Expressions\" />
    <Folder Include="SourceModelisation\Statements\" />
  </ItemGroup>

</Project>
