Public Enum TokenType

    LINESTART

    SYMBOL_PLUS
    SYMBOL_MINUS
    SYMBOL_MULTIPLICATE
    SYMBOL_DIVIDE
    SYMBOL_MODULO
    SYMBOL_POINT
    SYMBOL_COMMA
    SYMBOL_LEFT_PARENTHESIS
    SYMBOL_RIGHT_PARENTHESIS
    SYMBOL_LEFT_BRACKETS
    SYMBOL_RIGHT_BRACKETS
    SYMBOL_LEFT_BRACE
    SYMBOL_RIGHT_BRACE
    SYMBOL_COLON
    SYMBOL_GREATERTHAN
    SYMBOL_LESSTHAN
    SYMBOL_EQUAL
    SYMBOL_AT

    OP_MODULE_RESOLVER

    SOURCE_LINE

    VAL_INT
    VAL_FLOAT
    VAL_BOOL
    VAL_STRING
    VAL_FORMATED_STRING

    TEXT
    KEYWORD_FUNC
    KEYWORD_LET
    KEYWORD_IMPORT
    KEYWORD_USE
    KEYWORD_EXPORT
    KEYWORD_AS
    KEYWORD_PANIC
    KEYWORD_CONST
    KEYWORD_AND
    KEYWORD_OR
    KEYWORD_NOT
    KEYWORD_INCLUDE

End Enum
