Public Enum TokenType

    LINESTART

    SYMBOL_PLUS
    SYMBOL_MINUS
    SYMBOL_MULTIPLICATE
    SYMBOL_DIVIDE
    SYMBOL_MODULO
    SYMBOL_POINT
    SYMBOL_COMMA
    SYMBOL_LEFT_PARENTHESIS
    SYMBOL_RIGHT_PARENTHESIS
    SYMBOL_LEFT_BRACKETS
    SYMBOL_RIGHT_BRACKETS
    SYMBOL_COLON
    SYMBOL_GREATERTHAN
    SYMBOL_LESSTHAN
    SYMBOL_EQUAL

    VAL_INT
    VAL_FLOAT

    TEXT
    KEYWORD_FUNC

End Enum
