Namespace TypeSystem
    Public Enum RelationType
        RELATION_BRACKETS
        RELATION_ADD
        RELATION_SUB
        RELATION_MULT
        RELATION_DIV
        RELATION_MODULO
        RELATION_UNARY_MINUS
        RELATION_SET_BRACKETS
        RELATION_EQUAL
        RELATION_GREATERTHAN
        RELATION_GREATERTHANEQUAL
        RELATION_LESSTHAN
        RELATION_LESSTHANEQUAL
    End Enum

End Namespace