Public Enum TokenType

    WORD
    INT
    FLOAT
    STR

    OPERATOR_PLUS
    OPERATOR_MINUS
    OPERATOR_MULTIPLICATION
    OPERATOR_DIVISION
    OPERATOR_MODULO
    OPERATOR_IN
    OPERATOR_NOT
    OPERATOR_IS
    OPERATOR_EQUAL
    OPERATOR_LESSTHAN
    OPERATOR_LESSTHANEQUAL
    OPERATOR_MORETHAN
    OPERATOR_MORETHANEQUAL

    SYNTAX_LEFT_PARENTHESIS
    SYNTAX_RIGHT_PARENTHESIS
    SYNTAX_LEFT_BRACKET
    SYNTAX_RIGHT_BRACKET
    SYNTAX_DOT
    SYNTAX_COMMA
    SYNTAX_COLON
    SYNTAX_LINESTART

    KEYWORD_FUNC
    KEYWORD_CLASS
    KEYWORD_CONTRACT
    KEYWORD_SIGNS
    KEYWORD_ENUM
    KEYWORD_IF
    KEYWORD_ELSE
    KEYWORD_ELSEIF
    KEYWORD_WHILE
    KEYWORD_FOR
    KEYWORD_FROM
    KEYWORD_TO
    KEYWORD_IMPORT
    KEYWORD_EXCEPTION
    KEYWORD_RAISE
    KEYWORD_TRY
    KEYWORD_HANDLE
    KEYWORD_COOK
    KEYWORD_RELATION
    KEYWORD_LET
    KEYWORD_GET
    KEYWORD_SET
    KEYWORD_PRIMITIVE
    KEYWORD_REF
    KEYWORD_RETURN
    KEYWORD_EXPORT
    KEYWORD_BREAK
    KEYWORD_CONTINUE
    KEYWORD_NEW

    PRECOMPILE

End Enum
