
Namespace AST
    Public Class FormattedStringExpression
        Inherits ExpressionNode

        Private Value As String

        Public Sub New(Value As String, Location As Location)
            MyBase.New(Location)
            Me.Value = Value
        End Sub

        Public Overrides Function GetExpressionReturnType(Context As Context.Context) As TypeSystem.Type
            Return TypeSystem.Type.Str
        End Function

        Public Overrides Function CompileExpression(Writer As CWriter, Scope As Context.Scope) As String

            Dim SanitazedString As String = SanitizeString(Value)

            Dim FormatString As String = "" 'Used for the sprintf format string, will be generated by replacing the {expr} with %s
            Dim FormatArgsVariables As New List(Of String) 'Used for the sprintf arguments, ex: arg1, arg2, etc

            Dim Group As String = ""
            Dim BraceCount As Integer = 0

            For Each Letter In SanitazedString

                If Letter = "{" Then
                    If BraceCount = 0 Then
                        FormatString &= Group
                        Group = ""
                        BraceCount = 1
                    Else
                        Group &= Letter
                        BraceCount += 1
                    End If

                ElseIf Letter = "}" Then
                    BraceCount -= 1
                    If BraceCount = 0 Then
                        FormatString &= "%s"

                        Dim Tokens = Tokenizer.TokenizeExpression(Group, Location.File)
                        Dim Expression = AST.AbstractSyntaxTree.ParseExpression(Tokens)

                        Dim ExpressionType As TypeSystem.Type = Expression.GetExpressionReturnType(Scope)
                        If ExpressionType <> TypeSystem.Type.Str Then
                            Throw New TypeMismatchError(TypeSystem.Type.Str, ExpressionType, Location)
                        End If

                        Dim VariableName As String = CodeGen.Namer.Temp()
                        FormatArgsVariables.Add(VariableName)
                        Writer.WriteLine($"char* {VariableName} = {CodeGen.Write_LimStr_to_C(Expression.CompileExpression(Writer, Scope))};")

                        Group = ""

                    ElseIf BraceCount < 0 Then
                        Throw New SyntaxError("Unmatched closing brace in formatted string", Location)
                    Else
                        Group &= Letter
                    End If

                Else
                    Group &= Letter
                End If

            Next

            If BraceCount <> 0 Then
                Throw New SyntaxError("Unmatched braces in formatted string", Location)
            End If
            FormatString &= Group

            ' Get the length of the final string
            Dim LengthVariable As String = CodeGen.Namer.Temp() 'Get total string size for allocating memory
            Dim FormatArgs As String = If(FormatArgsVariables.Count > 0, ", " & String.Join(", ", FormatArgsVariables), "")

            Writer.WriteLine($"int {LengthVariable} = snprintf(NULL, 0, ""{FormatString}""{FormatArgs});")
            Dim ResultVariable As String = CodeGen.Namer.Temp()
            Writer.WriteLine($"char* {ResultVariable} = {CodeGen.AllocateLeaf("char", $"{LengthVariable} + 1")};")
            Writer.WriteLine($"snprintf({ResultVariable}, {LengthVariable} + 1, ""{FormatString}""{FormatArgs});")

            Return CodeGen.Write_C_to_LimStr(ResultVariable)

        End Function

        Private Shared Function SanitizeString(Value As String) As String
            Return Value.Replace("""", "\""").Replace(vbCr, "\r").Replace(vbLf, "\n").Replace(vbTab, "\t").Replace("%", "\%")
        End Function

    End Class
End Namespace